// Builds the two ResourceLoader modules, ES2017 CommonJS files that
// ResourceLoader runs as packageFiles (it passes require, module and exports):
//
//   ../resources/dist/gramophone.js         ext.gramophone: src/index.ts, everything a page of <sm2> buttons needs
//   ../resources/dist/gramophone.player.js  ext.gramophone.player: src/players.ts, the card player and the table row
//
// ext.gramophone exports the shared modules listed in src/index.ts (`export * from`), and
// ext.gramophone.player gets them with require('ext.gramophone') instead of a second copy.
//
// ES2017 is the newest syntax that MediaWiki 1.43's JavaScriptMinifier
// (wikimedia/minify 2.9.0) is documented to handle.
import * as esbuild from 'esbuild';
import { mkdir, readFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.join(here, 'src');
const dist = path.resolve(here, '../resources/dist');
const lucidePkg = JSON.parse(await readFile(path.join(here, 'node_modules/lucide/package.json'), 'utf8'));
const lucideLicense = (await readFile(path.join(here, 'node_modules/lucide/LICENSE'), 'utf8')).trim();

// The modules ext.gramophone shares, from the `export * from './name'` lines of src/index.ts.
const indexSource = await readFile(path.join(src, 'index.ts'), 'utf8');
const shared = new Set([...indexSource.matchAll(/^export \* from '\.\/([\w-]+)';$/gm)].map((m) => path.join(src, m[1] + '.ts')));

// Shadow DOM CSS is imported as a minified string.
const cssText = {
	name: 'css-text',
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			const source = await readFile(args.path, 'utf8');
			const { code } = await esbuild.transform(source, {
				loader: 'css',
				minify: true,
				target: ['chrome111', 'firefox128', 'safari16.4'],
			});
			return { contents: `export default ${JSON.stringify(code.trim())};`, loader: 'js' };
		});
	},
};

// In ext.gramophone.player, imports of a shared module come from ext.gramophone: they resolve to one module that
// reads each export once, so the code calls h() and not require('ext.gramophone').h().
const baseExports = Object.values(
	(
		await esbuild.build({
			entryPoints: [path.join(src, 'index.ts')],
			bundle: true,
			format: 'esm',
			write: false,
			metafile: true,
			outdir: dist,
			loader: { '.css': 'empty' },
		})
	).metafile.outputs,
)[0].exports;
const fromBase = {
	name: 'from-ext-gramophone',
	setup(build) {
		build.onResolve({ filter: /^\.\// }, (args) => {
			if (shared.has(path.join(args.resolveDir, args.path + '.ts'))) return { path: 'ext.gramophone', namespace: 'ext-gramophone' };
		});
		build.onResolve({ filter: /^ext\.gramophone$/, namespace: 'ext-gramophone' }, () => ({ path: 'ext.gramophone', external: true }));
		build.onLoad({ filter: /.*/, namespace: 'ext-gramophone' }, () => ({
			contents: `export const { ${baseExports.join(', ')} } = require('ext.gramophone');`,
			loader: 'js',
		}));
	},
};

const banner = (name) => `/*!
 * Gramophone client, ResourceLoader module ${name}.
 * Generated by client/build.mjs, do not edit. Source: client/src (TypeScript).
 *
 * Includes icons from Lucide ${lucidePkg.version} (https://lucide.dev):
 *
${lucideLicense
	.split('\n')
	.map((l) => (' * ' + l).trimEnd())
	.join('\n')}
 */`;

async function build(name, entry, outfile, plugins = []) {
	const result = await esbuild.build({
		entryPoints: [path.join(src, entry)],
		outfile: path.join(dist, outfile),
		bundle: true,
		format: 'cjs',
		platform: 'browser',
		target: 'es2017',
		charset: 'ascii',
		legalComments: 'none',
		banner: { js: banner(name) },
		// Readable output: ResourceLoader minifies again in production.
		minifySyntax: true,
		minifyWhitespace: false,
		minifyIdentifiers: false,
		treeShaking: true,
		metafile: true,
		plugins: [...plugins, cssText],
		logLevel: 'info',
	});
	// The source files that put code in the output.
	const inputs = Object.entries(Object.values(result.metafile.outputs)[0].inputs);
	return new Set(inputs.filter(([, v]) => v.bytesInOutput > 0).map(([f]) => path.resolve(here, f)));
}

// Only this build writes resources/dist: start empty, so a file it no longer makes cannot stay behind.
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
const base = await build('ext.gramophone', 'index.ts', 'gramophone.js');
const players = await build('ext.gramophone.player', 'players.ts', 'gramophone.player.js', [fromBase]);

// No source file may ship in both modules.
const twice = [...players].filter((f) => base.has(f));
if (twice.length) {
	console.error('FAIL: in both ext.gramophone and ext.gramophone.player:\n  ' + twice.map((f) => path.relative(here, f)).join('\n  '));
	process.exit(1);
}
